# Generated by Django 3.2.5 on 2021-07-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('raw_video', models.FileField(upload_to='raw')),
                ('preview_img', models.FileField(null=True, upload_to='previews')),
                ('video_mp4', models.FileField(null=True, upload_to='ready_mp4')),
                ('video_webm', models.FileField(null=True, upload_to='ready_webm')),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
